name: Setup api matrix
on:
  workflow_call:
    inputs:
      java-version:
        type: string
        required: false
        default: '25'
    outputs:
      matrix:
        value: ${{ jobs.create_matrix.outputs.task_output }}

permissions:
  contents: read
jobs:
  create_matrix:
    name: Create api matrix
    runs-on: ubuntu-latest
    outputs:
      task_output: ${{ steps.create_matrix.outputs.taskoutput }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '${{ inputs.java-version }}'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Create api matrix
        id: create_matrix
        shell: bash
        run: |
          TASKS=$(./gradlew tasks | awk '/- Write JSON/ {print $1}')
          echo "taskoutput=$(echo "$TASKS" | jq -cRn "{"project":[inputs]}")" >> $GITHUB_OUTPUT
